### ISSUE TITLE
Re-add requirements.txt for pip adherents

### ISSUE THREAD

**Issue by evanbiederstedt** [hms-dbmi/vitessce-data#111]
Thanks for the excellent work!

I'm someone who prefer to use pip, as I find it quicker when using virtualenv's. I see the appeal of conda, but I've never liked using it very much for a variety of reasons. 

Would it be possible to re-add the `requirements.txt` file and add installation instructions in the README? You could give users the option of using `conda` or `pip`. 

Naturally, if this is acceptable, I'm happy to make a PR myself. 

Thanks, Evan

**Comment by ilan-gold** [comment]
@evanbiederstedt I think we would happily accept a PR if you would like to make one.  Apologies for the slow response - I don't think it is in general characteristic!  Please request myself and @keller-mark as reviewers.
