### ISSUE TITLE
Raster data model proposal

### ISSUE THREAD

**Issue by manzt** [hms-dbmi/vitessce-data#88]
Here are some preliminary thoughts on defining a more complete `raster.json`. From [`vitessce/GLOSSARY.md`](https://github.com/hubmapconsortium/vitessce/blob/master/GLOSSARY.md): 

> A `raster` source will cause `SourcePublisher` to broadcast `raster.add` events which are subscribed to by `Spatial` components, and linked to particular layers.

The `raster.add` event also will subscribe a `Channel` component (for selecting colors, sliders, selections), which uses an `id` to publish changes in these events to particular layers in the `Spatial` component. 

Therefore, if multiple `channel` selection components are desired (i.e. viewing both ims and mxif data) these images should be described in separate `raster.json` schemas. However, if a single `channel/color` selector is desired, then we want to be flexible and allow for `raster.json` to describe multiple "images" which will not have different controllers. The following are several examples of a schema I envision:

### Example 1 -- Use case: single image url, single color/selector components

```json
{
  "id": "ims",
  "images": [
    {
      "url": "https://vitessce-data.storage.googleapis.com/0.0.24/master_release/spraggins/spraggins.ims.zarr",
      "type": "zarr",
      "name": "spraggins ims",
      "dimensions": [
        {
          "name": "mz",
          "type": "ordinal",
          "values": ["675.5366", "703.5722", "721.4766"]
        },
        { "name": "y", "type": "quantitative" },
        { "name": "x", "type": "quantitative" }
      ],
      "transform": {
        "scale": 20.0,
        "translate": [601, 951]
      }
    }
  ]
}
```

### Example 2 -- Use case: multiple image urls, single color/selector component + component to trigger `raster.add` event 

```json
{
  "id": "ims-mxif",
  "images": [
    {
      "id": "ims",
      "url": "https://vitessce-data.storage.googleapis.com/0.0.24/master_release/spraggins/spraggins.ims.zarr",
      "type": "zarr",
      "name": "spraggins ims",
      "dimensions": [
        {
          "name": "mz",
          "type": "ordinal",
          "values": ["675.5366", "703.5722", "721.4766"]
        },
        { "name": "y", "type": "quantitative" },
        { "name": "x", "type": "quantitative" }
      ],
      "transform": {
        "scale": 20.0,
        "translate": [601, 951]
      }
    },
    {
      "url": "https://vitessce-data.storage.googleapis.com/0.0.24/master_release/spraggins/mxif_pyramid",
      "type": "tiff",
      "name": "spraggins mxif",
      "dimensions": [
        {
          "name": "channel",
          "type": "nominal",
          "values": [
            "Cy3 - Synaptopodin (glomerular)",
            "Cy5 - THP (thick limb)",
            "DAPI - Hoescht (nuclei)",
            "FITC - Laminin (basement membrane)"
          ]
        },
        { "name": "y", "type": "quantitative" },
        { "name": "x", "type": "quantitative" }
      ],
      "isPyramid": true
    }
  ]
}
```

### Example 3-- Use case: multiple image urls, single color/selector component, shared attributes in source

Here rather than repeating shared information, we can set `dimensions` and `type` globally for the "images".

```json
{
  "id": "codex",
  "dimensions": [
    { "name": "channel", "type": "nominal", "values": [...] },
    { "name": "z", "type": "ordinal", "values": [...] },
    { "name": "y", "type": "quantitative" },
    { "name": "x", "type": "quantitative" }
  ],
  "type": "tiff",
  "images": [
      {"name": "x0 y0", "url": "..."},
      {"name": "x0 y1", "url": "..."},
      {"name": "x0 y2", "url": "..."},
      {"name": "x0 y3", "url": "..."},
      {"name": "x0 y4", "url": "..."}
  ]
}
```

### Example 4 -- Use case: multiple image urls, multiple color/selector components, no selector for to trigger `raster.add` event

Both schemas are valid, the former defines the "image"-specific information within the `images` key, but since it's just one image in this source, we can also define it using a flattened structure as in `mxif.raster.json`.

#### ims.raster.json
```json
{
  "id": "ims",
  "images": [
    {
      "url": "https://vitessce-data.storage.googleapis.com/0.0.24/master_release/spraggins/spraggins.ims.zarr",
      "type": "zarr",
      "name": "spraggins ims",
      "dimensions": [
        {
          "name": "mz",
          "type": "ordinal",
          "values": ["675.5366", "703.5722", "721.4766"]
        },
        { "name": "y", "type": "quantitative" },
        { "name": "x", "type": "quantitative" }
      ],
      "transform": {
        "scale": 20.0,
        "translate": [601, 951]
      }
    }
  ]
}
```

#### mxif.raster.json

```json
{
  "id": "mxif",
  "url": "https://vitessce-data.storage.googleapis.com/0.0.24/master_release/spraggins/mxif_pyramid",
  "type": "tiff",
  "name": "spraggins mxif",
  "dimensions": [
    {
      "name": "channel",
      "type": "nominal",
      "values": [
        "Cy3 - Synaptopodin (glomerular)",
        "Cy5 - THP (thick limb)",
        "DAPI - Hoescht (nuclei)",
        "FITC - Laminin (basement membrane)"
      ]
    },
    { "name": "y", "type": "quantitative" },
    { "name": "x", "type": "quantitative" }
  ],
  "isPyramid": true
}
```

**Comment by manzt** [comment]
They key here is that if a raster source includes multiple images, the shared `id` from the source will allow for the same channel/selection components to be used in the UI

**Comment by manzt** [comment]
Some additional thoughts. Keys like `transform` and `isPyramid` are optional, but perhaps rather than using things like `isPyramid` we should use more specific`type` keys: `tiff`, `zarr`, `tiff-pyramid`, `zarr-pyramid`.

One thing we haven't addressed in vitessce is how to define an initial `COLOR_CHANGE(id)` or `SLIDER_CHANGE(id)`. I think it would be appropriate to include an optional `initialState` property:

```javascript
initialState: {
    selections: [],
    sliderValues: [],
    colorValues: [],
}
```
but would ultimately like to this to come from some saved state config rather than a part of the raster source. 

Finally, as I think about this more, the `id` should really be outside of the `raster.json` since we have defined sources to have the following schema:

```javascript
const validSource = { 
    type: "raster", 
    url: "http://blahblah.com/raster.json",
    id: 'ims' 
};
```

**Comment by mccalluc** [comment]
Move to google doc for comments: https://docs.google.com/document/d/1FRBbSuqtD-phHazo3G0vYkaKi1YYBF7Mpm2YOYtfuLQ/edit#

**Comment by ilan-gold** [comment]
I might not get to engaging with this fully until the weekend/Monday.  I do have some thoughts though.
