### ISSUE TITLE
Visual bug in zarr image

### ISSUE THREAD

**Issue by ilan-gold** [hms-dbmi/vitessce-data#92]
I noticed this while working on the CODEX stuff.  Not sure what the move is here.  One option would be to fix the zarr for the release.  Another would be to use TIFF.  A final option would be to leave it as-is.  This is probably Nils' call.  It only appears at one zoom level.

I checked using a colormap to make sure it wasn't some weird deckgl wrapping thing, and it looks like that is the actual image data.  Every time we have run into this, it has been an unintended result of padding, so on that past experience, I'm putting this here as opposed to Viv.

<img width="788" alt="Screen Shot 2020-05-01 at 10 58 19 AM" src="https://user-images.githubusercontent.com/43999641/80872236-b2196c80-8c7e-11ea-9c23-4335db9eb94c.png">

<img width="1004" alt="Screen Shot 2020-05-01 at 10 58 55 AM" src="https://user-images.githubusercontent.com/43999641/80872234-af1e7c00-8c7e-11ea-9f82-3e8fdbc5f6f1.png">

CC: @manzt

**Comment by manzt** [comment]
I can't explore this right now, but my guess is that this is actually a bug with the zarr loader in viv (and not the source).  There is no `isTileInBounds` method in the zarr loader. I would `console.log` in the `getTile` function and look at the `x, y, z` requests. 

Is this in the vitessce demo? The sources are the same there and in viv I believe, so odd to see it in one place and not the other.

**Comment by manzt** [comment]
I can verify with napari that the source is not the issue:
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/24403730/80893322-5c08f100-8c9f-11ea-9ab8-3d8e31fe805e.png">

```bash
(py3.8) $ ipython
```

```python
In [2]: %gui qt                                                                

In [3]: import napari                                                          

In [4]: import dask.array as da                                                

In [5]: url = "https://vitessce-data.storage.googleapis.com/0.0.25/master_release/spraggins/spraggins.mxif.zarr"                                      

In [6]: pyramid = [da.from_zarr(f"{url}/{i}") for i in range(7)]               

In [7]: pyramid                                                                
Out[7]: 
[dask.array<from-zarr, shape=(4, 36040, 52660), dtype=uint16, chunksize=(1, 512, 512), chunktype=numpy.ndarray>,
 dask.array<from-zarr, shape=(4, 18020, 26330), dtype=uint16, chunksize=(1, 512, 512), chunktype=numpy.ndarray>,
 dask.array<from-zarr, shape=(4, 9010, 13165), dtype=uint16, chunksize=(1, 512, 512), chunktype=numpy.ndarray>,
 dask.array<from-zarr, shape=(4, 4505, 6582), dtype=uint16, chunksize=(1, 512, 512), chunktype=numpy.ndarray>,
 dask.array<from-zarr, shape=(4, 2252, 3291), dtype=uint16, chunksize=(1, 512, 512), chunktype=numpy.ndarray>,
 dask.array<from-zarr, shape=(4, 1126, 1645), dtype=uint16, chunksize=(1, 512, 512), chunktype=numpy.ndarray>,
 dask.array<from-zarr, shape=(4, 563, 822), dtype=uint16, chunksize=(1, 512, 512), chunktype=numpy.ndarray>]

In [8]: viewer = napari.Viewer()                                               

In [9]: viewer.add_image(pyramid)                                              
Out[9]: <Image layer 'Image' at 0x131d1edf0>
```

Note that all arrays decrease in a size by a factor of two at each level. There are no tiles in the space shown in your example. My guess is that either `deck.gl` is requesting a tile with positive coordinates and wrapping OR it's requesting negative tile indices (which are valid chunk selections in zarr) and zarr is responsible for the wrapping. If it is the latter, I would just add a check to `getTile` to ensure that all indices `(x, y, z)` are positive. Otherwise, we'll need to add a tile in bounds function as well.
